export const UserActionTypes = {
    ADD_CURRENT_USER: 'ADD_CURRENT_USER',
    DEL_CURRENT_USER: 'DEL_CURRENT_USER',
    IS_OLD_ENOUGH: 'IS_OLD_ENOUGH',
    IS_RELOAD_CARTITEMS: 'IS_RELOAD_CARTITEMS',
    IS_START_COUNTDOWN: 'IS_START_COUNTDOWN',
    HIDE_REFRESHED_TIMER_COUNTDOWN: 'HIDE_REFRESHED_TIMER_COUNTDOWN',
    CHANGE_TIMER: 'CHANGE_TIMER',
    CHECK_OUT_GLOBAL_STATUS: 'CHECK_OUT_GLOBAL_STATUS'
}